/* Generated by Yosys 0.9 (git sha1 1979e0b1, i686-w64-mingw32.static-g++ 5.5.0 -Os) */

(* top =  1  *)
(* src = "adder.v:8" *)
module adder(X, Y, S, cout);
  (* src = "adder.v:30|sfco.v:12" *)
  wire _00_;
  (* src = "adder.v:30|sfco.v:12" *)
  wire _01_;
  (* src = "adder.v:38|sfco.v:12" *)
  wire _02_;
  (* src = "adder.v:38|sfco.v:12" *)
  wire _03_;
  (* src = "adder.v:34|sfco.v:12" *)
  wire _04_;
  (* src = "adder.v:34|sfco.v:12" *)
  wire _05_;
  (* src = "adder.v:39|sfco.v:12" *)
  wire _06_;
  (* src = "adder.v:39|sfco.v:12" *)
  wire _07_;
  (* src = "adder.v:36|sfco.v:12" *)
  wire _08_;
  (* src = "adder.v:36|sfco.v:12" *)
  wire _09_;
  (* src = "adder.v:31|fco.v:10" *)
  wire _10_;
  (* src = "adder.v:31|fco.v:9" *)
  wire _11_;
  (* src = "adder.v:31|fco.v:9" *)
  wire _12_;
  (* src = "adder.v:32|fco.v:10" *)
  wire _13_;
  (* src = "adder.v:32|fco.v:9" *)
  wire _14_;
  (* src = "adder.v:32|fco.v:9" *)
  wire _15_;
  (* src = "adder.v:21|gph.v:10" *)
  wire _16_;
  (* src = "adder.v:21|gph.v:11" *)
  wire _17_;
  (* src = "adder.v:21|gph.v:12" *)
  wire _18_;
  (* src = "adder.v:22|gph.v:10" *)
  wire _19_;
  (* src = "adder.v:22|gph.v:11" *)
  wire _20_;
  (* src = "adder.v:22|gph.v:12" *)
  wire _21_;
  (* src = "adder.v:23|gph.v:10" *)
  wire _22_;
  (* src = "adder.v:23|gph.v:11" *)
  wire _23_;
  (* src = "adder.v:23|gph.v:12" *)
  wire _24_;
  (* src = "adder.v:24|gph.v:10" *)
  wire _25_;
  (* src = "adder.v:24|gph.v:11" *)
  wire _26_;
  (* src = "adder.v:24|gph.v:12" *)
  wire _27_;
  (* src = "adder.v:25|gph.v:10" *)
  wire _28_;
  (* src = "adder.v:25|gph.v:11" *)
  wire _29_;
  (* src = "adder.v:25|gph.v:12" *)
  wire _30_;
  (* src = "adder.v:26|gph.v:10" *)
  wire _31_;
  (* src = "adder.v:26|gph.v:11" *)
  wire _32_;
  (* src = "adder.v:26|gph.v:12" *)
  wire _33_;
  (* src = "adder.v:43" *)
  wire _34_;
  (* src = "adder.v:44" *)
  wire _35_;
  (* src = "adder.v:45" *)
  wire _36_;
  (* src = "adder.v:46" *)
  wire _37_;
  (* src = "adder.v:47" *)
  wire _38_;
  (* src = "adder.v:18" *)
  wire G10;
  (* src = "adder.v:30|sfco.v:9" *)
  wire \G10x.Ga ;
  (* src = "adder.v:30|sfco.v:10" *)
  wire \G10x.Gab ;
  (* src = "adder.v:30|sfco.v:9" *)
  wire \G10x.Gb ;
  (* src = "adder.v:30|sfco.v:9" *)
  wire \G10x.Pa ;
  (* src = "adder.v:18" *)
  wire G20;
  (* src = "adder.v:38|sfco.v:9" *)
  wire \G20x.Ga ;
  (* src = "adder.v:38|sfco.v:10" *)
  wire \G20x.Gab ;
  (* src = "adder.v:38|sfco.v:9" *)
  wire \G20x.Gb ;
  (* src = "adder.v:38|sfco.v:9" *)
  wire \G20x.Pa ;
  (* src = "adder.v:18" *)
  wire G30;
  (* src = "adder.v:34|sfco.v:9" *)
  wire \G30x.Ga ;
  (* src = "adder.v:34|sfco.v:10" *)
  wire \G30x.Gab ;
  (* src = "adder.v:34|sfco.v:9" *)
  wire \G30x.Gb ;
  (* src = "adder.v:34|sfco.v:9" *)
  wire \G30x.Pa ;
  (* src = "adder.v:18" *)
  wire G32;
  (* src = "adder.v:18" *)
  wire G40;
  (* src = "adder.v:39|sfco.v:9" *)
  wire \G40x.Ga ;
  (* src = "adder.v:39|sfco.v:10" *)
  wire \G40x.Gab ;
  (* src = "adder.v:39|sfco.v:9" *)
  wire \G40x.Gb ;
  (* src = "adder.v:39|sfco.v:9" *)
  wire \G40x.Pa ;
  (* src = "adder.v:18" *)
  wire G50;
  (* src = "adder.v:36|sfco.v:9" *)
  wire \G50x.Ga ;
  (* src = "adder.v:36|sfco.v:10" *)
  wire \G50x.Gab ;
  (* src = "adder.v:36|sfco.v:9" *)
  wire \G50x.Gb ;
  (* src = "adder.v:36|sfco.v:9" *)
  wire \G50x.Pa ;
  (* src = "adder.v:18" *)
  wire G54;
  (* src = "adder.v:31|fco.v:6" *)
  wire \GP32.Ga ;
  (* src = "adder.v:31|fco.v:7" *)
  wire \GP32.Gab ;
  (* src = "adder.v:31|fco.v:6" *)
  wire \GP32.Gb ;
  (* src = "adder.v:31|fco.v:6" *)
  wire \GP32.Pa ;
  (* src = "adder.v:31|fco.v:7" *)
  wire \GP32.Pab ;
  (* src = "adder.v:31|fco.v:6" *)
  wire \GP32.Pb ;
  (* src = "adder.v:32|fco.v:6" *)
  wire \GP54.Ga ;
  (* src = "adder.v:32|fco.v:7" *)
  wire \GP54.Gab ;
  (* src = "adder.v:32|fco.v:6" *)
  wire \GP54.Gb ;
  (* src = "adder.v:32|fco.v:6" *)
  wire \GP54.Pa ;
  (* src = "adder.v:32|fco.v:7" *)
  wire \GP54.Pab ;
  (* src = "adder.v:32|fco.v:6" *)
  wire \GP54.Pb ;
  (* src = "adder.v:21|gph.v:8" *)
  wire \GPH0.G ;
  (* src = "adder.v:21|gph.v:8" *)
  wire \GPH0.H ;
  (* src = "adder.v:21|gph.v:8" *)
  wire \GPH0.P ;
  (* src = "adder.v:21|gph.v:7" *)
  wire \GPH0.x ;
  (* src = "adder.v:21|gph.v:7" *)
  wire \GPH0.y ;
  (* src = "adder.v:22|gph.v:8" *)
  wire \GPH1.G ;
  (* src = "adder.v:22|gph.v:8" *)
  wire \GPH1.H ;
  (* src = "adder.v:22|gph.v:8" *)
  wire \GPH1.P ;
  (* src = "adder.v:22|gph.v:7" *)
  wire \GPH1.x ;
  (* src = "adder.v:22|gph.v:7" *)
  wire \GPH1.y ;
  (* src = "adder.v:23|gph.v:8" *)
  wire \GPH2.G ;
  (* src = "adder.v:23|gph.v:8" *)
  wire \GPH2.H ;
  (* src = "adder.v:23|gph.v:8" *)
  wire \GPH2.P ;
  (* src = "adder.v:23|gph.v:7" *)
  wire \GPH2.x ;
  (* src = "adder.v:23|gph.v:7" *)
  wire \GPH2.y ;
  (* src = "adder.v:24|gph.v:8" *)
  wire \GPH3.G ;
  (* src = "adder.v:24|gph.v:8" *)
  wire \GPH3.H ;
  (* src = "adder.v:24|gph.v:8" *)
  wire \GPH3.P ;
  (* src = "adder.v:24|gph.v:7" *)
  wire \GPH3.x ;
  (* src = "adder.v:24|gph.v:7" *)
  wire \GPH3.y ;
  (* src = "adder.v:25|gph.v:8" *)
  wire \GPH4.G ;
  (* src = "adder.v:25|gph.v:8" *)
  wire \GPH4.H ;
  (* src = "adder.v:25|gph.v:8" *)
  wire \GPH4.P ;
  (* src = "adder.v:25|gph.v:7" *)
  wire \GPH4.x ;
  (* src = "adder.v:25|gph.v:7" *)
  wire \GPH4.y ;
  (* src = "adder.v:26|gph.v:8" *)
  wire \GPH5.G ;
  (* src = "adder.v:26|gph.v:8" *)
  wire \GPH5.H ;
  (* src = "adder.v:26|gph.v:8" *)
  wire \GPH5.P ;
  (* src = "adder.v:26|gph.v:7" *)
  wire \GPH5.x ;
  (* src = "adder.v:26|gph.v:7" *)
  wire \GPH5.y ;
  (* src = "adder.v:15" *)
  wire [5:0] Gii;
  (* src = "adder.v:17" *)
  wire [5:0] Hii;
  (* src = "adder.v:18" *)
  wire P10;
  (* src = "adder.v:18" *)
  wire P32;
  (* src = "adder.v:18" *)
  wire P54;
  (* src = "adder.v:16" *)
  wire [5:0] Pii;
  (* src = "adder.v:12" *)
  output [5:0] S;
  (* src = "adder.v:10" *)
  input [5:0] X;
  (* src = "adder.v:11" *)
  input [5:0] Y;
  (* src = "adder.v:13" *)
  output cout;
  assign _00_ = \G10x.Pa  & (* src = "adder.v:30|sfco.v:12" *) \G10x.Gb ;
  assign _01_ = \G10x.Ga  | (* src = "adder.v:30|sfco.v:12" *) _00_;
  assign _02_ = \G20x.Pa  & (* src = "adder.v:38|sfco.v:12" *) \G20x.Gb ;
  assign _03_ = \G20x.Ga  | (* src = "adder.v:38|sfco.v:12" *) _02_;
  assign _04_ = \G30x.Pa  & (* src = "adder.v:34|sfco.v:12" *) \G30x.Gb ;
  assign _05_ = \G30x.Ga  | (* src = "adder.v:34|sfco.v:12" *) _04_;
  assign _06_ = \G40x.Pa  & (* src = "adder.v:39|sfco.v:12" *) \G40x.Gb ;
  assign _07_ = \G40x.Ga  | (* src = "adder.v:39|sfco.v:12" *) _06_;
  assign _08_ = \G50x.Pa  & (* src = "adder.v:36|sfco.v:12" *) \G50x.Gb ;
  assign _09_ = \G50x.Ga  | (* src = "adder.v:36|sfco.v:12" *) _08_;
  assign _10_ = \GP32.Pa  & (* src = "adder.v:31|fco.v:10" *) \GP32.Pb ;
  assign _11_ = \GP32.Pa  & (* src = "adder.v:31|fco.v:9" *) \GP32.Gb ;
  assign _12_ = \GP32.Ga  | (* src = "adder.v:31|fco.v:9" *) _11_;
  assign _13_ = \GP54.Pa  & (* src = "adder.v:32|fco.v:10" *) \GP54.Pb ;
  assign _14_ = \GP54.Pa  & (* src = "adder.v:32|fco.v:9" *) \GP54.Gb ;
  assign _15_ = \GP54.Ga  | (* src = "adder.v:32|fco.v:9" *) _14_;
  assign _16_ = \GPH0.x  & (* src = "adder.v:21|gph.v:10" *) \GPH0.y ;
  assign _17_ = \GPH0.x  | (* src = "adder.v:21|gph.v:11" *) \GPH0.y ;
  assign _18_ = \GPH0.x  ^ (* src = "adder.v:21|gph.v:12" *) \GPH0.y ;
  assign _19_ = \GPH1.x  & (* src = "adder.v:22|gph.v:10" *) \GPH1.y ;
  assign _20_ = \GPH1.x  | (* src = "adder.v:22|gph.v:11" *) \GPH1.y ;
  assign _21_ = \GPH1.x  ^ (* src = "adder.v:22|gph.v:12" *) \GPH1.y ;
  assign _22_ = \GPH2.x  & (* src = "adder.v:23|gph.v:10" *) \GPH2.y ;
  assign _23_ = \GPH2.x  | (* src = "adder.v:23|gph.v:11" *) \GPH2.y ;
  assign _24_ = \GPH2.x  ^ (* src = "adder.v:23|gph.v:12" *) \GPH2.y ;
  assign _25_ = \GPH3.x  & (* src = "adder.v:24|gph.v:10" *) \GPH3.y ;
  assign _26_ = \GPH3.x  | (* src = "adder.v:24|gph.v:11" *) \GPH3.y ;
  assign _27_ = \GPH3.x  ^ (* src = "adder.v:24|gph.v:12" *) \GPH3.y ;
  assign _28_ = \GPH4.x  & (* src = "adder.v:25|gph.v:10" *) \GPH4.y ;
  assign _29_ = \GPH4.x  | (* src = "adder.v:25|gph.v:11" *) \GPH4.y ;
  assign _30_ = \GPH4.x  ^ (* src = "adder.v:25|gph.v:12" *) \GPH4.y ;
  assign _31_ = \GPH5.x  & (* src = "adder.v:26|gph.v:10" *) \GPH5.y ;
  assign _32_ = \GPH5.x  | (* src = "adder.v:26|gph.v:11" *) \GPH5.y ;
  assign _33_ = \GPH5.x  ^ (* src = "adder.v:26|gph.v:12" *) \GPH5.y ;
  assign _34_ = Hii[1] ^ (* src = "adder.v:43" *) Gii[0];
  assign _35_ = Hii[2] ^ (* src = "adder.v:44" *) G10;
  assign _36_ = Hii[3] ^ (* src = "adder.v:45" *) G20;
  assign _37_ = Hii[4] ^ (* src = "adder.v:46" *) G30;
  assign _38_ = Hii[5] ^ (* src = "adder.v:47" *) G40;
  assign S[0] = Hii[0];
  assign S[1] = _34_;
  assign S[2] = _35_;
  assign S[3] = _36_;
  assign S[4] = _37_;
  assign S[5] = _38_;
  assign cout = G50;
  assign \GPH0.x  = X[0];
  assign \GPH0.y  = Y[0];
  assign Gii[0] = \GPH0.G ;
  assign Pii[0] = \GPH0.P ;
  assign Hii[0] = \GPH0.H ;
  assign \GPH0.G  = _16_;
  assign \GPH0.P  = _17_;
  assign \GPH0.H  = _18_;
  assign \GPH1.x  = X[1];
  assign \GPH1.y  = Y[1];
  assign Gii[1] = \GPH1.G ;
  assign Pii[1] = \GPH1.P ;
  assign Hii[1] = \GPH1.H ;
  assign \GPH1.G  = _19_;
  assign \GPH1.P  = _20_;
  assign \GPH1.H  = _21_;
  assign \GPH2.x  = X[2];
  assign \GPH2.y  = Y[2];
  assign Gii[2] = \GPH2.G ;
  assign Pii[2] = \GPH2.P ;
  assign Hii[2] = \GPH2.H ;
  assign \GPH2.G  = _22_;
  assign \GPH2.P  = _23_;
  assign \GPH2.H  = _24_;
  assign \GPH3.x  = X[3];
  assign \GPH3.y  = Y[3];
  assign Gii[3] = \GPH3.G ;
  assign Pii[3] = \GPH3.P ;
  assign Hii[3] = \GPH3.H ;
  assign \GPH3.G  = _25_;
  assign \GPH3.P  = _26_;
  assign \GPH3.H  = _27_;
  assign \GPH4.x  = X[4];
  assign \GPH4.y  = Y[4];
  assign Gii[4] = \GPH4.G ;
  assign Pii[4] = \GPH4.P ;
  assign Hii[4] = \GPH4.H ;
  assign \GPH4.G  = _28_;
  assign \GPH4.P  = _29_;
  assign \GPH4.H  = _30_;
  assign \GPH5.x  = X[5];
  assign \GPH5.y  = Y[5];
  assign Gii[5] = \GPH5.G ;
  assign Pii[5] = \GPH5.P ;
  assign Hii[5] = \GPH5.H ;
  assign \GPH5.G  = _31_;
  assign \GPH5.P  = _32_;
  assign \GPH5.H  = _33_;
  assign \G10x.Ga  = Gii[1];
  assign \G10x.Pa  = Pii[1];
  assign \G10x.Gb  = Gii[0];
  assign G10 = \G10x.Gab ;
  assign \G10x.Gab  = _01_;
  assign \GP32.Ga  = Gii[3];
  assign \GP32.Pa  = Pii[3];
  assign \GP32.Gb  = Gii[2];
  assign \GP32.Pb  = Pii[2];
  assign G32 = \GP32.Gab ;
  assign P32 = \GP32.Pab ;
  assign \GP32.Gab  = _12_;
  assign \GP32.Pab  = _10_;
  assign \GP54.Ga  = Gii[5];
  assign \GP54.Pa  = Pii[5];
  assign \GP54.Gb  = Gii[4];
  assign \GP54.Pb  = Pii[4];
  assign G54 = \GP54.Gab ;
  assign P54 = \GP54.Pab ;
  assign \GP54.Gab  = _15_;
  assign \GP54.Pab  = _13_;
  assign \G30x.Ga  = G32;
  assign \G30x.Pa  = P32;
  assign \G30x.Gb  = G10;
  assign G30 = \G30x.Gab ;
  assign \G30x.Gab  = _05_;
  assign \G50x.Ga  = G54;
  assign \G50x.Pa  = P54;
  assign \G50x.Gb  = G30;
  assign G50 = \G50x.Gab ;
  assign \G50x.Gab  = _09_;
  assign \G20x.Ga  = Gii[2];
  assign \G20x.Pa  = Pii[2];
  assign \G20x.Gb  = G10;
  assign G20 = \G20x.Gab ;
  assign \G20x.Gab  = _03_;
  assign \G40x.Ga  = Gii[4];
  assign \G40x.Pa  = Pii[4];
  assign \G40x.Gb  = G30;
  assign G40 = \G40x.Gab ;
  assign \G40x.Gab  = _07_;
endmodule
